### ISSUE TITLE
Add composer

### ISSUE THREAD

**Issue by tarioch** [aineko-m/iveeCore#1]
Did you think about adding a composer config so that iveeCore can be installed through it?

**Comment by aineko-m** [comment]
I haven't so far because iveeCore doesn't depend on any other libraries and installing it via git is trivial (and Composer can't handle the required platform packages, it can at most check for them). But I'll consider it just because it seems to be popular.

**Comment by tarioch** [comment]
Added pull request #2

**Comment by aineko-m** [comment]
Nice, the first pull request :) I'll review it tomorrow.
Glancing over it two things come to mind:
- I'm debating if I want to remove iveeCore/Config.php from .gitignore. If we did, people that still want to use the copied and edited template config file will run into merge conflicts on future updates. Also it just transfers the need to store the configuration to whomever is using the library.
- Feel free to add yourself as author.

**Comment by aineko-m** [comment]
@tarioch I don't seem to have the option to send you a private message on Github so here it goes:
I'm assuming you are using iveeCore so I'd be very interested in knowing what your use case is and also if you're planning on doing more code work. Please get in touch in Eve or post on the Eve-O thread.
