### ISSUE TITLE
Error after eve patch 2016-06-14

### ISSUE THREAD

**Issue by zomar76** [aineko-m/iveeCore#7]
Hello,

I'm using iveeCore inside Symfony 1.4 application.

After 2016-06-14 patch (https://developers.eveonline.com/blog/article/crest-renovations-2016-06) I got error:

PHP Fatal error:  Call to undefined method iveeCrest\Responses\BaseResponse::getRegionCollection() in /mnt/data/apache/............../lib/task/eveCrestTask.class.php on line 115

I know that many  urls are wrong after patch. 

But why method is undefined? I Assume that is problem with inheritance.

I know that baseUrl is in Config class. Where are defined other parts of urls?

Are you planning update of script?

BR 
Zomar

**Comment by aineko-m** [comment]
This is due to the incremented CREST root representation version, which doesn't get mapped to the proper class and defaults to BaseResponse. This is already fixed in the dev branch. A new release will be out soon.
